config/routes.rb
Rails.application.routes.draw do
  resources :positions
  resources :magazines
  resources :oenologists
  devise_for :users
  resources :wine_strains
  resources :strains
  resources :wines

  root to: "wines#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wine_strains, dependent: :destroy
    has_many :strains, through: :wine_strains
    has_many :wine_oenologists, dependent: :destroy
    has_many :oenologists, through: :wine_oenologists

    def addStrainPercentage(strain_percentage)
        strain_percentage.each do |strain_id, strain_percentage|
            if strain_percentage != ''
                temp_strain = self.wine_strains.where(strain_id: strain_id).first
                temp_strain.strain_percentage = strain_percentage
                temp_strain.save
            end
        end
    end

    def oenologist_name
        oenologists.map do |wine_oenologist|
            wine_oenologist.oeno_name
        end.join(', ')
    end 

    def strainnames_and_percentages
        strain_list = []
        wine_strains.map do |ws|
           strain_list << [ws.strain.strain_name, ws.strain_percentage]
        end

        strain_list.sort_by {|strain| strain[0]}.map do |strain_info|
            "#{strain_info[0]} (#{strain_info[1]}%)"
        end.join (', ')
    end



end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit update destroy ]
  before_action :authorize_admin!, except: [:index]

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        @wine.addStrainPercentage(params[:wine][:strain_percentage])
        format.html { redirect_to @wine, notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:wine_name, :score, {oenologist_ids: []}, {strain_ids: []}, :strain_percentage)
    end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :wine_name %>
    <%= form.text_field :wine_name %>
  </div>

  <div class="field">
    <%= form.label :oenologists %>
    <%= form.collection_check_boxes(:oenologist_ids, Oenologist.all.order(:age), :id, :oeno_name) do |oe| %>
            <%= oe.label class: "label-checkbox" do %>
              <%= oe.check_box + oe.text %>
            <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :strains %>
    <%= form.collection_check_boxes(:strain_ids, Strain.where(available:true), :id, :strain_name) do |strain| %>
            <%= strain.label class: "label-checkbox" do %>
              <%= strain.check_box + strain.text %>
              <%= form.label :strain_percentage %> 
              <%= text_field("wine[strain_percentage]", strain.value, size: 1) %>%
            <% end %>

    <% end %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score, size: 2 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Wine name</th>
      <th>Strain info</th>
      <th>Score</th>
      <th>Oenologist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.wine_name %></td>
        <td><%= wine.strainnames_and_percentages %></td>
        <td><%= wine.score %></td>
        <td><%= wine.oenologist_name %></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>
<%= link_to 'Oenologist List', oenologists_path %>
<%= link_to 'Strain List', strains_path %>
<%= link_to 'Log out', destroy_user_session_path, method: :delete %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wine name:</strong>
  <%= @wine.wine_name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @wine.score %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>